### ISSUE TITLE
NotImplementedError: Unsupported operation

### ISSUE THREAD

**Issue by DartLazer** [adafruit/Adafruit_CircuitPython_IRRemote#45]
A very good day to everyoen here.

I'm trying to make an IR Receiver/Sender on a raspberry PiCo.

I'm using the code from your example: [https://github.com/adafruit/Adafruit_CircuitPython_IRRemote/blob/master/examples/irremote_transmit.py](https://pastebin.com/L0zWDnUD)

EDIT:
I put my code in a pastebin because soemhow the markup woudl get really weird here:
[https://pastebin.com/L0zWDnUD](https://pastebin.com/L0zWDnUD)

Trying to run this on my raspberry PICO is giving me the following error:
`code.py output:
Traceback (most recent call last):
  File "code.py", line 20, in <module>
NotImplementedError: Unsupported operation`

I've been trying different pins etc but I keep getting this error.
Any clues?

**Comment by tannewt** [comment]
PulseOut isn't implemented on the RP2040 yet. Please follow https://github.com/adafruit/circuitpython/issues/4111 to see when it is.
