### ISSUE TITLE
irremote_simpletest show decoded value is None

### ISSUE THREAD

**Issue by njuFerret** [adafruit/Adafruit_CircuitPython_IRRemote#47]
when update irremote from 4.0.6 to 4.1.0, irremote_simletest.py not work as expect.

the  member function  ` def decode_bits(self, pulses): `  of  `GenericDecode` has no return value, 

maybe line with `return result.code` should be added to the last of the function.

**Comment by tannewt** [comment]
Sounds right to me. Please make a PR and we'll review it. Thanks!
