### ISSUE TITLE
Rewrite `read_pulses` to be non-blocking

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_IRRemote#6]
Currently it waits until it gets a signal before moving on. It reads pulses until it sees one that's long enough, in a loop that waits forever.

To make it non-blocking, consider relying on the circular buffer of pulseio.

**Comment by apatt** [comment]
made this possible:
https://github.com/adafruit/Adafruit_CircuitPython_IRRemote/pull/11

@tannewt

**Comment by tannewt** [comment]
Fixed by #11
