### ISSUE TITLE
I tried running the code with Circuitpython in a Pi Pico W and it doesn't work

### ISSUE THREAD

**Issue by mr-pepe69** [adafruit/Adafruit_CircuitPython_IRRemote#60]
the code i used instead was:

```python
import pulseio
import board
import adafruit_irremote
pulsein = pulseio.PulseIn(board.GP0, maxlen=120, idle_state=True)
decoder = adafruit_irremote.GenericDecode()
but1 = "(255, 0, 93, 162)"
while True:
    pulses = decoder.read_pulses(pulsein)
    print("Heard", len(pulses), "Pulses:", pulses) 
    try:

        code = decoder.decode_bits(pulses)
        codestr = str(code)
        print("Decoded:", code)
        if codestr == but1:
            print('uwu')
        else:
            print('no')
        
    except adafruit_irremote.FailedToDecode:  # unusual short code!
        print("NEC repeat!")
        continue
    except adafruit_irremote.IRDecodeException as e:     # failed to decode
        print("Failed to decodeunu: ", e.args)
        continue
    print("----------------------------")
```

i trully don't understand why changing the except made it to  work (i also added a couple things to make it usefull. not good code, but does the trick) i'm kinda new to this, so if there is something needed just tell me. (i read the except from the source code and i got the example from there too.)

**Comment by tekktrik** [comment]
Can you post the exact code that causes problems, for comparison?

**Comment by mr-pepe69** [comment]
i can also add the part of the source code that i used to fix the problem if you want.
the part that says `.IRNECRepeatException` doesn't work. but it works if i replace it with `FailedToDecode`
The thing is that the whole thing is a try statement. but when i get an error with `.IRNECRepeatException` it just stop the execution.

```python
    except adafruit_irremote.IRNECRepeatException:  # unusual short code!
        print("NEC repeat!")
    except adafruit_irremote.IRDecodeException as e:     # failed to decode
        print("Failed to decode: ", e.args)
```

**Comment by tekktrik** [comment]
Looks like a new exception got added and that perhaps the example wasn't updated properly, I can fix that.

**Comment by mr-pepe69** [comment]
> Looks like a new exception got added and that perhaps the example wasn't updated properly, I can fix that.

i thought about that, but i found it weird considering it was the first thing you see...
anyways, i'm not sure if the second exception is working, i didn't found it while testing, so maybe you should try that too.
pd: i'm not 100% sure but maybe the second exception is redundant.
